# Generated by Django 6.0.6 on 2026-08-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperiodo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('salario', models.FloatField()),
                ('percepciones', models.FloatField()),
                ('deducciones', models.FloatField()),
                ('total', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas_registro', to='empleados.empleado')),
            ],
            options={
                'db_table': 'nomina',
            },
        ),
    ]
