# Generated by Django 6.0.6 on 2026-07-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('estudios', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperiodo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('salario', models.FloatField()),
                ('perceciones', models.FloatField()),
                ('deducciones', models.FloatField()),
                ('total', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empleados.empleado')),
            ],
        ),
    ]
