# Generated by Django 6.0.5 on 2026-06-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellido', models.CharField()),
                ('sexo', models.CharField()),
                ('tipo', models.CharField()),
            ],
        ),
    ]
