# Generated by Django 6.0.6 on 2026-07-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios_usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
