# Generated by Django 6.0.6 on 2026-07-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
