# Generated by Django 6.0.5 on 2026-07-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
