# Generated by Django 6.0.5 on 2026-07-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'clientes_cliente',
                'managed': False,
            },
        ),
    ]
