# Generated by Django 6.0.5 on 2026-07-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='clientes',
        ),
    ]
