# Generated by Django 6.0.6 on 2026-07-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_clientes',
        ),
    ]
